export interface DrinkData {
  name: string;
  description: string;
  price: number;
  cost: number;
  stock: number;
  image: string;
  category: string;
}

export const drinksData: DrinkData[] = [
  // Coffee
  {
    name: 'Espresso',
    description: 'Rich and bold Italian espresso shot made from premium arabica beans',
    price: 25000,
    cost: 8000,
    stock: 100,
    image: '/drinks/espresso.svg',
    category: 'Coffee',
  },
  {
    name: 'Cappuccino',
    description: 'Classic Italian coffee with steamed milk and foam, topped with cocoa powder',
    price: 35000,
    cost: 12000,
    stock: 100,
    image: '/drinks/cappuccino.svg',
    category: 'Coffee',
  },
  {
    name: 'Caffe Latte',
    description: 'Smooth espresso with steamed milk and light foam, perfect for any time',
    price: 38000,
    cost: 13000,
    stock: 100,
    image: '/drinks/latte.svg',
    category: 'Coffee',
  },
  {
    name: 'Americano',
    description: 'Espresso diluted with hot water for a smooth, rich coffee experience',
    price: 28000,
    cost: 9000,
    stock: 100,
    image: '/drinks/americano.svg',
    category: 'Coffee',
  },
  {
    name: 'Mocha',
    description: 'Espresso with chocolate syrup, steamed milk, and whipped cream',
    price: 42000,
    cost: 15000,
    stock: 80,
    image: '/drinks/mocha.svg',
    category: 'Coffee',
  },
  {
    name: 'Caramel Macchiato',
    description: 'Vanilla-flavored latte with caramel drizzle and espresso',
    price: 45000,
    cost: 16000,
    stock: 80,
    image: '/drinks/caramel-macchiato.svg',
    category: 'Coffee',
  },
  {
    name: 'Iced Coffee',
    description: 'Refreshing cold brew coffee served over ice',
    price: 32000,
    cost: 11000,
    stock: 90,
    image: '/drinks/iced-coffee.svg',
    category: 'Coffee',
  },
  {
    name: 'Vietnamese Coffee',
    description: 'Strong coffee with sweetened condensed milk, served hot or iced',
    price: 35000,
    cost: 12000,
    stock: 70,
    image: '/drinks/vietnamese-coffee.svg',
    category: 'Coffee',
  },

  // Tea
  {
    name: 'English Breakfast Tea',
    description: 'Classic black tea blend, perfect for morning or afternoon',
    price: 20000,
    cost: 6000,
    stock: 100,
    image: '/drinks/english-breakfast.svg',
    category: 'Tea',
  },
  {
    name: 'Green Tea',
    description: 'Light and refreshing Japanese green tea with antioxidants',
    price: 22000,
    cost: 7000,
    stock: 100,
    image: '/drinks/green-tea.svg',
    category: 'Tea',
  },
  {
    name: 'Jasmine Tea',
    description: 'Fragrant green tea infused with jasmine flowers',
    price: 24000,
    cost: 8000,
    stock: 80,
    image: '/drinks/jasmine-tea.svg',
    category: 'Tea',
  },
  {
    name: 'Earl Grey',
    description: 'Black tea flavored with bergamot oil, aromatic and sophisticated',
    price: 23000,
    cost: 7500,
    stock: 90,
    image: '/drinks/earl-grey.svg',
    category: 'Tea',
  },
  {
    name: 'Chamomile Tea',
    description: 'Calming herbal tea made from chamomile flowers',
    price: 25000,
    cost: 8000,
    stock: 70,
    image: '/drinks/chamomile.svg',
    category: 'Tea',
  },
  {
    name: 'Thai Tea',
    description: 'Sweet and creamy Thai-style tea with condensed milk',
    price: 28000,
    cost: 9000,
    stock: 85,
    image: '/drinks/thai-tea.svg',
    category: 'Tea',
  },
  {
    name: 'Matcha Latte',
    description: 'Premium Japanese matcha powder with steamed milk',
    price: 40000,
    cost: 14000,
    stock: 75,
    image: '/drinks/matcha-latte.svg',
    category: 'Tea',
  },
  {
    name: 'Iced Lemon Tea',
    description: 'Refreshing black tea with fresh lemon and ice',
    price: 25000,
    cost: 8000,
    stock: 90,
    image: '/drinks/iced-lemon-tea.svg',
    category: 'Tea',
  },

  // Juice & Smoothies
  {
    name: 'Orange Juice',
    description: 'Freshly squeezed orange juice, packed with vitamin C',
    price: 28000,
    cost: 10000,
    stock: 60,
    image: '/drinks/orange-juice.svg',
    category: 'Juice',
  },
  {
    name: 'Mango Smoothie',
    description: 'Tropical mango blended with yogurt and honey',
    price: 35000,
    cost: 13000,
    stock: 50,
    image: '/drinks/mango-smoothie.svg',
    category: 'Juice',
  },
  {
    name: 'Strawberry Banana Smoothie',
    description: 'Sweet strawberries and banana blended with milk',
    price: 38000,
    cost: 14000,
    stock: 50,
    image: '/drinks/strawberry-banana.svg',
    category: 'Juice',
  },
  {
    name: 'Green Detox Juice',
    description: 'Healthy blend of spinach, apple, cucumber, and lemon',
    price: 40000,
    cost: 15000,
    stock: 40,
    image: '/drinks/green-detox.svg',
    category: 'Juice',
  },
  {
    name: 'Watermelon Juice',
    description: 'Refreshing fresh watermelon juice, perfect for hot days',
    price: 30000,
    cost: 11000,
    stock: 55,
    image: '/drinks/watermelon-juice.svg',
    category: 'Juice',
  },
  {
    name: 'Avocado Smoothie',
    description: 'Creamy avocado blended with milk and chocolate syrup',
    price: 42000,
    cost: 16000,
    stock: 45,
    image: '/drinks/avocado-smoothie.svg',
    category: 'Juice',
  },
  {
    name: 'Mixed Berry Smoothie',
    description: 'Antioxidant-rich blend of blueberries, raspberries, and strawberries',
    price: 45000,
    cost: 17000,
    stock: 40,
    image: '/drinks/mixed-berry.svg',
    category: 'Juice',
  },
  {
    name: 'Carrot Ginger Juice',
    description: 'Fresh carrot juice with a hint of ginger for immunity boost',
    price: 32000,
    cost: 12000,
    stock: 50,
    image: '/drinks/carrot-ginger.svg',
    category: 'Juice',
  },

  // Soft Drinks & Others
  {
    name: 'Fresh Coconut Water',
    description: 'Natural coconut water straight from young coconuts',
    price: 25000,
    cost: 10000,
    stock: 60,
    image: '/drinks/coconut-water.svg',
    category: 'Refreshments',
  },
  {
    name: 'Lemonade',
    description: 'Classic homemade lemonade with fresh lemons',
    price: 22000,
    cost: 7000,
    stock: 80,
    image: '/drinks/lemonade.svg',
    category: 'Refreshments',
  },
  {
    name: 'Iced Chocolate',
    description: 'Rich chocolate drink served cold with whipped cream',
    price: 35000,
    cost: 12000,
    stock: 70,
    image: '/drinks/iced-chocolate.svg',
    category: 'Refreshments',
  },
  {
    name: 'Mineral Water',
    description: 'Premium bottled mineral water',
    price: 10000,
    cost: 3000,
    stock: 200,
    image: '/drinks/mineral-water.svg',
    category: 'Refreshments',
  },
  {
    name: 'Sparkling Water',
    description: 'Refreshing carbonated mineral water',
    price: 15000,
    cost: 5000,
    stock: 150,
    image: '/drinks/sparkling-water.svg',
    category: 'Refreshments',
  },
  {
    name: 'Hot Chocolate',
    description: 'Rich and creamy hot chocolate with marshmallows',
    price: 32000,
    cost: 11000,
    stock: 75,
    image: '/drinks/hot-chocolate.svg',
    category: 'Refreshments',
  },
  {
    name: 'Vanilla Milkshake',
    description: 'Classic vanilla ice cream blended into a thick shake',
    price: 38000,
    cost: 14000,
    stock: 60,
    image: '/drinks/vanilla-milkshake.svg',
    category: 'Refreshments',
  },
  {
    name: 'Chocolate Milkshake',
    description: 'Decadent chocolate ice cream shake topped with whipped cream',
    price: 40000,
    cost: 15000,
    stock: 60,
    image: '/drinks/chocolate-milkshake.svg',
    category: 'Refreshments',
  },
];
